# Config file for go-test-coverage github action.

profile: coverage.txt # set via github action
local-prefix: github.com/argally/golang-testing/isprimecli
threshold:
  file: 80
  total: 80
## when token is not specified (value '') this feature is turned off
  ## in this example badge is created and committed only for main branch
  git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
  ## name of branch where badges are stored
  ## ideally this should be orphan branch (see below how to create this branch)
  git-branch: badges 

